"""Create chat tables with cascade delete

Revision ID: 406aeda0f9a6
Revises: c92ee27139df
Create Date: 2025-04-17 22:17:35.691754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406aeda0f9a6'
down_revision: Union[str, None] = 'c92ee27139df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
