"""Add cancelled_by to reservations

Revision ID: 58a2870d0ec7
Revises: b61acc28051d
Create Date: 2025-03-26 23:43:48.166654

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "58a2870d0ec7"
down_revision: Union[str, None] = "b61acc28051d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column("reservations", sa.Column("cancelled_by", sa.String(), nullable=True))
    # ### end Alembic commands ###
    pass

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reservations", "cancelled_by")
    # ### end Alembic commands ###
