"""Initial new migrations

Revision ID: b61acc28051d
Revises: c026038da09b
Create Date: 2025-03-25 23:14:10.109013

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b61acc28051d"
down_revision: Union[str, None] = "c026038da09b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("books", "cover_image", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("books", "cover_image", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
